# -*- coding: utf-8 -*-
"""EDA_Airbnb_Booking Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XM5bspNUQyI1KB7_UozqRs95DCWTkDB0

# **Project Name**    - **Exploratory data analysis of Airbnb booking pattern**

##### **Project Type**    - EDA
##### **Contribution**    - Individual

# **Project Summary -**

This exploratory data analysis (EDA) project focused on understanding the factors that influence Airbnb booking patterns and trends, The objective was to provide valuable insights to hosts and travellers, enabling them to enhance their experience on the platform. The dataset used in this analysis contained information about Airbnb bookings, including geographical coordinates, room type, availability, prices, neighbourhood details, and review metrics.

The project began with a thorough understanding of the dataset, which comprised 48,884 rows and 16 columns. Manipulations were performed to remove irrelevant columns and handle missing values, resulting in a clean dataset ready for analysis.

Thirteen different visualizations were employed to extract insights and facilitate discussion. These visualizations covered various aspects of the data, ranging from average and median prices based on location and room type to the distribution of numeric features and the correlation between different variables. Each visualization provided specific insight that could potentially impact business strategies positively or negatively.

Some key findings from the visualizations include: 
1) The mean price of entire home/apartment room types was higher across all locations, with Manhattan having the highest prices overall. This insight could guide pricing strategies and promotional schemes to attract  more customers.
2)Outliers were identified in variables like minimum nights and calculated host listing count, suggesting the need for outlier management to improve booking accuracy and customer experience.
3) The scatter plots of price vs number of reviews indicated an inverse relationship, implying that lower-priced accommodations tend to attract more reviews. Adjusting pricing strategies could potentially drive positive customer reviews and satisfaction.
4) The correlation matrix revealed relationships between variables such as calculated host listing count, number of reviews, and minimum nights.  These insights could guide optimization of hosting strategies and resource allocation.
5) The pie charts illustrated the distribution of room types and services across different neighbourhood groups. Understanding these distributions could inform market targeting resource allocation, and expansion opportunities.

Based on these insights, several recommendations can be made to improve business outcomes:

1) Implement attractive promotional schemes and discounts for entire home/apartment room types to mitigate the potential negative impact of higher prices.
2) Address outliers and anomalies in the dataset to enhance booking accuracy and customer experience.
3) Optimize marketing efforts, pricing strategies, and resource allocation based on the preferences and demand for specific room types in each neighbourhood group.
4) Monitor and respond to customer feedback to enhance customer satisfaction and drive positive growth.
5) Identify potential expansion opportunities in neighbouhrhood groups with lower service offerings to capture a large market share.

In conclusion, this EDA project has successfully delved into the vast trove of Airbnb booking data, unearthing invaluable insights that prove beneficial for both hosts and travellers alike. Leveraging these insightful findings and implementing the recommended strategies enables business to finely tune their pricing models, enhance marketing efforts, and optimize resource allocation, thereby fostering positive growth and an elevated level of customer satisfaction. It is of utmost importance to maintain a diligent and regular monitoring of data trends and actively seek customer feedback in order to remain competitive within the ever-evolving landscape of the dynamics Airbnb market.

# **GitHub Link -**

https://github.com/ankitdandiwala/Airbnb-Booking-Analysis

# **Problem Statement**

**This exploratory data analysis project aims to uncover valuable insights from the Airbnb booking dataset, enabling informed decisions for the client**

#### **Define Your Business Objective?**

**To identify the key factors that influence Airbnb booking patterns and trends in order to provide insights that can be used by the client grow their business.**

## ***1. Know Your Data***
"""

# Import Libraries
import pandas as pd
from pylab import *
import seaborn as sns
import matplotlib.pyplot as plt

"""### Dataset Loading"""

# Access data from the drive
from google.colab import drive
drive.mount('/content/drive')
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Airbnb_NYC_2019.csv')

"""### Viewing Dataframe"""

# View dataframe
df.head()

#View tail
df.tail()

"""### Dataset Rows & Columns count"""

# View shape of the dataframe
df.shape

"""### Dataset Information"""

# View information of the dataframe
df.info

"""#### Duplicate Values"""

# View if duplicate rows exist
df[df.duplicated()].count

"""#### Missing Values/Null Values"""

# Vieweing null values in each column
df.isnull().sum()

"""### What did you know about your dataset?

Dataset represents information about the Airbnb booking that includes geographical coordinates of the property, types of room, availability, price, details of neighbourhood alongwith number of reviews received till  the  last date of review, and rate  of review. The shape of the dataset is 48895 rows and 16 columns. Some features of the dataset include null values, however, dataset does not possess duplicate values. Dataset contains categorical data too.

## ***2. Understanding Your Variables***
"""

# Dataset Columns
df.columns

# Dataset Describe
df.describe()

"""### Variables Description

Dataset includes integer, float and object type data. Most of the variables are of numerical types. Price variable possess higher standard deviation, which indicates that there are  significant variations in price across different room services. Moreover, it is to be noted that the minimum price of the room is zero, which seems errorneous data. The minimum number of nights for the booking is one at some service provider however the same is 1250, which seems unrealistic. Other variables seem have acceptable standard deviation with minimum and maximum values.

### Check Unique Values for each variable.
"""

# Viewing unique values in each columns
[print(df[i].value_counts()) for i in df.columns]

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Dropping columns not be included in visualization
df = df.drop(['name','host_name','last_review'],axis = 1)

# Replacing Null values in reviewes_per_month with zero
df.fillna({'reviews_per_month': 0}, inplace = True)
df.isnull().sum()

# Excluding data corresponding to zero price and checking if rows have been reduced
df = df.loc[df['price']>0]
len(df)

"""### What all manipulations have you done and insights you found?

Following three manipulations have been made:
1) Few columns called 'name', 'host_name', 'last_review' have been removed since they are not going to be the part of analysis.
2) Null values contained by the column 'reviewe_per_month' are replaced with zero.
3) Data frame is modified excluding rows which had zero price for room service. This way final length of dataset became 48884.

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### 1. Location wise and room type wise average price - Bar Chart
"""

# Creating and visualizing dataframe gourping mean price as per location and neighbourhood group
average_price_loc_roomtype=df.groupby(['neighbourhood_group','room_type'])['price'].mean().unstack()
average_price_loc_roomtype.plot.bar()
plt.title('Average price per location and room type')
plt.xlabel('Neighburhood group')
plt.ylabel('Average price ($)')
plt.legend(title = 'Room type', loc = 'upper right')
plt.show()

"""##### 1. Why did you pick the specific chart?

To see what location has mean high price for a specific room type.

##### 2. What is/are the insight(s) found from the chart?

It is found that the mean price of entire home/apartment type room service is higher for all location. Also, it is to be noted that the mean price is higher at Manhattan for all types of room service.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

A significantly higher price of entire home/apartment might lead to negative growth in the business model for the non-seasonal days.

#### 2. Location wise and room type wise median of price - Bar chart
"""

# Creating and visualizing dataframe gourping mean price as per location and neighbourhood group
average_price_loc_roomtype=df.groupby(['neighbourhood_group','room_type'])['price'].median().unstack()
average_price_loc_roomtype.plot.bar()
plt.title('Median of price per location and room type')
plt.xlabel('Neighburhood group')
plt.ylabel('Median of price ($)')
plt.legend(title = 'Room type', loc = 'upper right')
plt.show()

"""##### 1. Why did you pick the specific chart?

To see what location has high median price for a specific room type.

##### 2. What is/are the insight(s) found from the chart?

It is found that the median price of entire home/apartment type room service is higher and the same is lower for shared room for all neighbourhood group.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Higher prices for entire home/apartment rentals could potentially have a detrimental impact on the business's growth. implementing attractive promotional schemes and discounts for entire home/apartment type room service can help mitigate the potential negative impact of higher prices

#### 3. Distribution of numeric features in the dataframe - Box plot
"""

# Creating box plots of those columns having numeric values
f, ax = plt.subplots(2, 3, figsize = (15,10))
sns.boxplot(y = 'price', data = df, ax=ax[0,0])
sns.boxplot(y = 'minimum_nights', data = df, ax=ax[0,1])
sns.boxplot(y = 'number_of_reviews', data = df, ax=ax[0,2])
sns.boxplot(y = 'reviews_per_month', data = df, ax=ax[1,0])
sns.boxplot(y = 'calculated_host_listings_count', data = df, ax=ax[1,1])
sns.boxplot(y = 'availability_365', data = df, ax=ax[1,2])
plt.suptitle("Distribution of numeric feature in dataframe")
plt.show()

"""##### 1. Why did you pick the specific chart?

Box plot has been chosen to check the outliers in plotted variables.

##### 2. What is/are the insight(s) found from the chart?

Most of the values are far from each other except the variables 'availability_365'. it suggests that the dataset needs pre-processing in terms of dealing with outliers.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

Analyzing the minimum_nights variable can help identify outliers and anomalies, allowing for targeted investigations and potential improvements in customer experience. Addressing unusual values can enhance the accuracy and reliability of booking information.

#### 4. Distribution of numeric features in the data frame - Distribution plot
"""

# Creating distribution plots of those columns having numeric values
f, ax = plt.subplots(2, 3, figsize = (15,10))
sns.distplot(df['price'], ax=ax[0,0])
sns.distplot(df['minimum_nights'], ax=ax[0,1])
sns.distplot(df['number_of_reviews'], ax=ax[0,2])
sns.distplot(df['reviews_per_month'], ax=ax[1,0])
sns.distplot(df['calculated_host_listings_count'], ax=ax[1,1])
sns.distplot(df['availability_365'], ax=ax[1,2])
plt.suptitle("Distribution of numeric feature in dataframe")
plt.show()

"""##### 1. Why did you pick the specific chart?

Distribution plots are used to visualize variable distributions.

##### 2. What is/are the insight(s) found from the chart?

Variables exhibit right-skewed distribution with concentration towards lower values and some extreme values.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

The insights highlight the importance of monitoring extreme values and skewed distributions. By regularly monitoring these  aspects, business can detect any issues that might arise.

#### 5. Number of hosts for various neighbourhood group and room type - Bar plot
"""

# Creating and visualizing dataframe grouping mean price as per room type and neighbourhood group
number_of_host_loc_roomtype=df.groupby(['neighbourhood_group','room_type'])['host_id'].count().unstack()
number_of_host_loc_roomtype.plot.bar()
plt.title('Number of host per location and roomtype')
plt.ylabel('Neighbourhood group')
plt.ylabel('Count of host')
plt.legend(title = 'Room type', loc = 'upper right')
plt.show()

"""##### 1. Why did you pick the specific chart?

The bar chart was chosen to compare the number of hosts across neighbourhood groups and room types.

##### 2. What is/are the insight(s) found from the chart?

Insights from the chart include: 1) Manhattan has the most entire home/apartment type room services, while private rooms are more common in Bronx, Brooklyn, Queens and Ten island. 2) Bronx and Ten island have fewer rooms in all types. 3) Shared room type services are less common overall.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

The insights can help target marketing efforts, adjust pricing strategies, and enhance customer satisfaction.

#### 6. Visualize neighbourhood group using map - Scatter plot

---
"""

# Visualizing locations wise service on map
sns.scatterplot(x ='longitude',y ='latitude',hue = 'neighbourhood_group', data = df)
plt.title("Listing by neighbourhood group")
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.legend(title = 'Neighbourhood group', loc = 'upper left')
plt.show()

"""##### 1. Why did you pick the specific chart?

The scatter plot is chosen because it is effective for visualizing the geographical distribution. As can be seen, scatter plot displays the latitude and longitude coordinates of the Airbnb listings and use color to present different neighbourhoods.

##### 2. What is/are the insight(s) found from the chart?

The insights from the chart include understanding the spatial distribution of Airbnb listings and identifying patterns or variations acoss neighbourhoods.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

The gained insights can help create a positive business impact by informing market targeting, pricing strategy, and resource allocation decisions. Negative growth insights depend on specific factors in the data and require further analysis.

#### 7. Visualize room type using map - Scatter plot
"""

# Visualizing room type on map
sns.scatterplot(x ='longitude',y ='latitude',hue = 'room_type', data = df)
plt.title("Room type")
plt.xlabel('Longitude')
plt.ylabel('Latitude')
plt.legend(title = 'Room type', loc = 'upper left')
plt.show()

"""##### 1. Why did you pick the specific chart?

The scatter plot of latitude and longitude with room type is chosen to visualize the geographic distribution of different room types. It allows for the examination of spatial patterns and helps identify any clustering or variations in room types across different locations.

##### 2. What is/are the insight(s) found from the chart?

When viewing private rooms and enitre home/apartment type room services, the points seem scattered at some location and dense at other locations, indicating needs of proper management.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

The scatter plot reveals that there is not significant concentration of any type of rooms in a particular area. However, such presentation might help businesses optimize their property acquisition to cater the preference the of potential customers in specific areas.

#### 8. Number of rooms for each room type and neighbourhood group
"""

# Plotting number of specific rooms per neighbourhood group
sns.catplot(x = 'room_type', kind = 'count', hue = 'neighbourhood_group', data = df )
plt.title('Number of rooms per neighbourhood group')
plt.xlabel('Room type')
plt.ylabel('Count')
plt.legend(title = 'Neighbourhood group')
plt.show()

"""##### 1. Why did you pick the specific chart?

The categorical plot with count presentation and hue encoding for neighbourhood group is chosen to visualize the distribution of different room types across the neighbourhood groups.

##### 2. What is/are the insight(s) found from the chart?

The charts reveal that shared rooms are less compared to private rooms and entire home across all neighbourhoods group. Moreover, chart highlights that both Manhattan and Brooklyn have a higher number of rooms compared to the other neighbourhoods group.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

The insights that Manhattan and Brooklyn have a higher number of rooms suggests that these areas might have higher demand from customers. Businesses can leverage these details to optimize their pricing strategies, allocate resources effectively.

#### 9. Price vs Number of reviews
"""

# Visualizing Price vs number of reviews
sns.scatterplot(x ='number_of_reviews',y ='price', data = df)
plt.title("Price Vs Number of reviews")
plt.xlabel('Number of reviews')
plt.ylabel('Price ($)')
plt.show()

"""##### 1. Why did you pick the specific chart?

A scatter plot is chosen here as it allows to examine the correlation between two continuous variables.

##### 2. What is/are the insight(s) found from the chart?

The scatter plot suggests an inverse relationship between price and number of reviews. Moreover, the scatter plot's density is higher in the lower price range and lower number of reviews range, indicating that there are more instances where lower-priced accommodations have a relatively smaller number of reviews.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

It is understood that the lower-priced accommodations tend to attract more reviews. Businesses can consider adjusting their pricing strategy to attract more customers and generate positive reviews.

#### 10. Correlation matrix
"""

# Dropping columns not be included in visualization
df_numeric = df.drop(['id','host_id','neighbourhood_group','neighbourhood','room_type','latitude','longitude'],axis = 1)

# Visualizing Price vs number of reviews
sns.heatmap(df_numeric.corr(), square = True,  cmap='RdYlGn')
plt.title("Correlation matrix of numerical features")
plt.show()

"""##### 1. Why did you pick the specific chart?

A correlation matrix is an effective way to visualize the relationships between multiple variables in a date set.

##### 2. What is/are the insight(s) found from the chart?

The negative correlation between calculated host listing and number of reviews, as well as between minimum nights and reviews per month  are identified. On other hand, there is a positive correlation between number of reviews and reviews per month.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

The negative correlation between the calculated host listing and the number of reviews, and the minimum nights and the review per month, can guide business in optimizing their hosting strategies and identifying the areas where adjustments can be made to attract more reviews.

#### 11. Relationship between different numeric data - Pair plot
"""

# Relationship between different numeric data using Pair plot
df_interest = df_numeric.drop(['minimum_nights', 'calculated_host_listings_count'], axis = 1)
sns.pairplot(df_interest)
plt.title("Pair plot")
plt.show()

"""##### 1. Why did you pick the specific chart?

The pair plot was chosen to visualize the relationships and patterns between the variables: price, number of reviews, reviews per month and availability.

##### 2. What is/are the insight(s) found from the chart?

The price and reviews per month, and price and number of reviews exhibit negative correlation, whereas number of reviews and reviews per month exhibit a positive relationship.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

The gained insights from the pair plot can help identifying the potential anomalies in the data and understanding the distribution and relationship between variables.

#### 12. Number of rooms types in each neighbourhod group - Pie Chart
"""

#Creating dataframe grouping neighbourhood group and room type
df_neighbour = df.groupby(['neighbourhood_group','room_type']).agg({'id':'count'}).reset_index()
#Making array of uniqye neighbourhood group
unique_neighbour = df_neighbour['neighbourhood_group'].unique()
#making pie chart separately for neighbourhood group representing fraction of types of room in the group
for i in unique_neighbour:
    df_i=df_neighbour[df_neighbour['neighbourhood_group'] == i]
    mylabels = ["Entire home/apt", "Private room", "Shared room"]
    plt.figure()
    plt.pie(df_i['id'], labels = mylabels, startangle = 90)
    plt.title(f'Number of room types in {i}')
    plt.show()

"""##### 1. Why did you pick the specific chart?

The pie plots were chosen to visually represent the distribution of room type services within each niehgbourhood group.

##### 2. What is/are the insight(s) found from the chart?

The pie charts reveal the composition of room type services within each neighbourhood group. They show the relative distribution of entire home/apartment, private room and shared room type services. For all neighbourhood groups, the share of entire home/apartment type rooms and private rooms type services are higher campared to shared room type services.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

The gained insights can help in understanding the demand and preferences or different room types in each neighbourhood group. The information can be valuable for the marketing strategies, pricing decisions, and resource allocation.

#### 13. Number of services in each neighbourhood group - Pie Chart
"""

df_neighbourgroup = df_neighbour.groupby('neighbourhood_group').agg({'id':"sum"})
plt.pie(df_neighbourgroup['id'], labels = unique_neighbour, startangle = 90)
plt.title('Number of services in each neighbourhood group')
plt.show()

"""##### 1. Why did you pick the specific chart?

The pie plot was chosen to visually represent the distribution of room type services in each niehgbourhood group.

##### 2. What is/are the insight(s) found from the chart?

The pie chart provides insights into the overall distribution of services among the neighbourhood groups. By examining the proportions of services in each slice of the pie, It can be identified that Manhattan and Brooklyn have comparatively more total services, contrary to that, all three neighbourhood groups have lower services.

##### 3. Will the gained insights help creating a positive business impact? 
Are there any insights that lead to negative growth? Justify with specific reason.

By leveraging the information from the pie chart, business can make informed decision regarding resource allocation, marketing efforts and expansion plans.

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ? 
Explain Briefly.

Based on the insights gained from the visualizations and data analysis, following are the suggestion to the client to achieve business objective:

1) pricing strategy: Based on the location type-wise average and median prices, it is evident that entire home/apartment type room services end to have higher prices, especially in Manhattan. To create a positive business impact, client can consider implementing attractive promotional schemes and discounts for entire home/apartment type room services to mitigate the potential negative impact (higher prices). This strategy can attract more customers and enhance customer satisfaction.

2) Outliers management: The box plot analysis revealed outliers in the variables minimum nights and calculated host listing count. To create a positive business impact, it is important to address these outliers and anomalies in the dataset. By conducting further investigations and implementing measures to improve customer experience and booking accuracy, client can get enhanced overall reliability of the service.

3) Market Targeting and Resource Allocation: The bar plots and scatter plots provide valuable insights into the distribution of room types, number of hosts, and neighbourhood groups. Utilize this information to optimize client's marketing efforts, pricing strategies, and resource allocation.

4) Customer reviews and satisfactions: The correlation matrix and pair plots highlight the relationships between variables such as price, number of reviews, and reviews per month. The insights gained can help you optimize your hosting strategies and identify areas for improvement to attract more reviews. By monitoring and responding to customer feedback, you can enhance customer satisfaction and drive positive growth for the business.

5) Expansion opportunities: The pie charts showcasing the number of services in each neighbourhood group provide insights into the overall distribution of services. Manhattan and Brooklyn stand out as having comparatively more total services. Use this information to identify potential expansion opportunities in other neighbourhood groups with lower services. By strategically expanding your services to these areas, you can capture a larger market share and drive positive business growth.

# **Conclusion**

Based on the analysis of the Airbnb booking data, it is evident that there are several factors that influence booking patterns and trends. 
 

*   Manhattan and Brooklyn have a noticeably higher number of services compared to other neighbourhood groups. This insight allows us to pinpoint potential expansion opportunities in neighbourhood groups that currently have fewer services.

*   Price and number of reviews, and price and reviews per month are inversely proportional to each other. By monitoring and responding to customer feedback, customer satisfaction can be enhanced and client can drive positive growth for the business.

*   The box plot analysis revealed outliers in the variables minimum nights. It seems unrealistic that the minimum night for the booking is 1250. It is important to eliminate the anomalies and outliers.

*   The correlation matrix reveals the positive correlation between number of reviews and reviews per month. Any of the variable can be removed before applying the model in order to reduce the computing power and complexity.
"""